/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ConfigurerRouteImport } from './routes/configurer'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as InspirationsRouteImport } from './routes/inspirations'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PhilosophieRouteImport } from './routes/philosophie'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CircuitSlugRouteImport } from './routes/circuit.$slug'
import { Route as InspirationsSlugRouteImport } from './routes/inspirations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurerRoute = ConfigurerRouteImport.update({
  id: '/configurer',
  path: '/configurer',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationsRoute = InspirationsRouteImport.update({
  id: '/inspirations',
  path: '/inspirations',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophieRoute = PhilosophieRouteImport.update({
  id: '/philosophie',
  path: '/philosophie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitSlugRoute = CircuitSlugRouteImport.update({
  id: '/circuit/$slug',
  path: '/circuit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationsSlugRoute = InspirationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InspirationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/configurer': typeof ConfigurerRoute
  '/galerie': typeof GalerieRoute
  '/inspirations': typeof InspirationsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/philosophie': typeof PhilosophieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/circuit/$slug': typeof CircuitSlugRoute
  '/inspirations/$slug': typeof InspirationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/configurer': typeof ConfigurerRoute
  '/galerie': typeof GalerieRoute
  '/inspirations': typeof InspirationsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/philosophie': typeof PhilosophieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/circuit/$slug': typeof CircuitSlugRoute
  '/inspirations/$slug': typeof InspirationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/configurer': typeof ConfigurerRoute
  '/galerie': typeof GalerieRoute
  '/inspirations': typeof InspirationsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/philosophie': typeof PhilosophieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/circuit/$slug': typeof CircuitSlugRoute
  '/inspirations/$slug': typeof InspirationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgv'
    | '/configurer'
    | '/galerie'
    | '/inspirations'
    | '/mentions-legales'
    | '/philosophie'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/circuit/$slug'
    | '/inspirations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgv'
    | '/configurer'
    | '/galerie'
    | '/inspirations'
    | '/mentions-legales'
    | '/philosophie'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/circuit/$slug'
    | '/inspirations/$slug'
  id:
    | '__root__'
    | '/'
    | '/cgv'
    | '/configurer'
    | '/galerie'
    | '/inspirations'
    | '/mentions-legales'
    | '/philosophie'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/circuit/$slug'
    | '/inspirations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CgvRoute: typeof CgvRoute
  ConfigurerRoute: typeof ConfigurerRoute
  GalerieRoute: typeof GalerieRoute
  InspirationsRoute: typeof InspirationsRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PhilosophieRoute: typeof PhilosophieRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CircuitSlugRoute: typeof CircuitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurer': {
      id: '/configurer'
      path: '/configurer'
      fullPath: '/configurer'
      preLoaderRoute: typeof ConfigurerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirations': {
      id: '/inspirations'
      path: '/inspirations'
      fullPath: '/inspirations'
      preLoaderRoute: typeof InspirationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophie': {
      id: '/philosophie'
      path: '/philosophie'
      fullPath: '/philosophie'
      preLoaderRoute: typeof PhilosophieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuit/$slug': {
      id: '/circuit/$slug'
      path: '/circuit/$slug'
      fullPath: '/circuit/$slug'
      preLoaderRoute: typeof CircuitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirations/$slug': {
      id: '/inspirations/$slug'
      path: '/$slug'
      fullPath: '/inspirations/$slug'
      preLoaderRoute: typeof InspirationsSlugRouteImport
      parentRoute: typeof InspirationsRoute
    }
  }
}

interface InspirationsRouteChildren {
  InspirationsSlugRoute: typeof InspirationsSlugRoute
}

const InspirationsRouteChildren: InspirationsRouteChildren = {
  InspirationsSlugRoute: InspirationsSlugRoute,
}

const InspirationsRouteWithChildren = InspirationsRoute._addFileChildren(
  InspirationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CgvRoute: CgvRoute,
  ConfigurerRoute: ConfigurerRoute,
  GalerieRoute: GalerieRoute,
  InspirationsRoute: InspirationsRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PhilosophieRoute: PhilosophieRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CircuitSlugRoute: CircuitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
