/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurerRouteImport } from './routes/configurer'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as InspirationsRouteImport } from './routes/inspirations'
import { Route as InspirationsSlugRouteImport } from './routes/inspirations.$slug'
import { Route as PhilosophieRouteImport } from './routes/philosophie'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurerRoute = ConfigurerRouteImport.update({
  id: '/configurer',
  path: '/configurer',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationsRoute = InspirationsRouteImport.update({
  id: '/inspirations',
  path: '/inspirations',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationsSlugRoute = InspirationsSlugRouteImport.update({
  id: '/inspirations/$slug',
  path: '/inspirations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophieRoute = PhilosophieRouteImport.update({
  id: '/philosophie',
  path: '/philosophie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurer': typeof ConfigurerRoute
  '/galerie': typeof GalerieRoute
  '/inspirations': typeof InspirationsRoute
  '/inspirations/$slug': typeof InspirationsSlugRoute
  '/philosophie': typeof PhilosophieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurer': typeof ConfigurerRoute
  '/galerie': typeof GalerieRoute
  '/inspirations': typeof InspirationsRoute
  '/inspirations/$slug': typeof InspirationsSlugRoute
  '/philosophie': typeof PhilosophieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurer': typeof ConfigurerRoute
  '/galerie': typeof GalerieRoute
  '/inspirations': typeof InspirationsRoute
  '/inspirations/$slug': typeof InspirationsSlugRoute
  '/philosophie': typeof PhilosophieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configurer'
    | '/galerie'
    | '/inspirations'
    | '/inspirations/$slug'
    | '/philosophie'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configurer'
    | '/galerie'
    | '/inspirations'
    | '/inspirations/$slug'
    | '/philosophie'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/configurer'
    | '/galerie'
    | '/inspirations'
    | '/inspirations/$slug'
    | '/philosophie'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurerRoute: typeof ConfigurerRoute
  GalerieRoute: typeof GalerieRoute
  InspirationsRoute: typeof InspirationsRoute
  InspirationsSlugRoute: typeof InspirationsSlugRoute
  PhilosophieRoute: typeof PhilosophieRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurer': {
      id: '/configurer'
      path: '/configurer'
      fullPath: '/configurer'
      preLoaderRoute: typeof ConfigurerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirations': {
      id: '/inspirations'
      path: '/inspirations'
      fullPath: '/inspirations'
      preLoaderRoute: typeof InspirationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirations/$slug': {
      id: '/inspirations/$slug'
      path: '/$slug'
      fullPath: '/inspirations/$slug'
      preLoaderRoute: typeof InspirationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophie': {
      id: '/philosophie'
      path: '/philosophie'
      fullPath: '/philosophie'
      preLoaderRoute: typeof PhilosophieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurerRoute: ConfigurerRoute,
  GalerieRoute: GalerieRoute,
  InspirationsRoute: InspirationsRoute,
  InspirationsSlugRoute: InspirationsSlugRoute,
  PhilosophieRoute: PhilosophieRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance>>
  }
}
